server.port=5432

spring.datasource.url=jdbc:postgresql://localhost:8080/university_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true